{{- range (.Values.kubetorchConfig.deployment_namespaces | default list) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetorch-data-store
  namespace: {{ . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetorch-data-store
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubetorch-data-store
        {{- with $.Values.kubetorchConfig.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $.Values.kubetorchConfig.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $.Values.dataStore.serviceAccount }}
      serviceAccountName: {{ $.Values.dataStore.serviceAccount }}
      {{- end }}

      {{- with $.Values.kubetorchConfig.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $.Values.kubetorchConfig.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- if or $.Values.kubetorchConfig.affinity $.Values.dataStore.affinity }}
      affinity:
        {{- with $.Values.kubetorchConfig.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.dataStore.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- if or $.Values.kubetorchConfig.nodeSelector $.Values.dataStore.nodeSelector }}
      nodeSelector:
        {{- with $.Values.kubetorchConfig.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.dataStore.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- if or $.Values.kubetorchConfig.tolerations $.Values.dataStore.tolerations }}
      tolerations:
        {{- with $.Values.kubetorchConfig.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.dataStore.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      containers:
        - name: data-store
          image: "ghcr.io/run-house/kubetorch-data-store:{{ $.Values.dataStore.tag }}"
          imagePullPolicy: {{ $.Values.dataStore.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_ENABLED
              value: "{{ $.Values.logStreaming.enabled }}"
          ports:
            - containerPort: 873   # rsync daemon
            - containerPort: 8080  # HTTP/WebSocket tunnel
            - containerPort: {{ $.Values.dataStore.metadataPort | default 8081 }}  # Metadata server API
            - containerPort: 3100  # Loki log storage
          volumeMounts:
            - name: data-store-storage
              mountPath: /data
            - name: rsyncd-config
              mountPath: /etc/rsyncd.conf
              subPath: rsyncd.conf
            {{- if $.Values.logStreaming.enabled }}
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
            {{- end }}
          resources:
            requests:
              cpu: {{ $.Values.dataStore.cpu.request }}
              memory: {{ $.Values.dataStore.memory.request }}
              ephemeral-storage: {{ $.Values.dataStore.ephemeralStorage.request }}
      volumes:
        - name: data-store-storage
          persistentVolumeClaim:
            claimName: kubetorch-data-store-pvc
        - name: rsyncd-config
          configMap:
            name: kubetorch-rsyncd-config
        {{- if $.Values.logStreaming.enabled }}
        - name: loki-config
          configMap:
            name: kubetorch-loki-config
        {{- end }}
{{- end }}
