{{- if .Values.dataStore.cleanupCron.enabled }}
{{- range (.Values.kubetorchConfig.deployment_namespaces | default list | concat (list .Release.Namespace) | uniq) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-store-cleaner
  namespace: {{ . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-store-cleaner-role
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-store-cleaner-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: data-store-cleaner
    namespace: {{ . }}
roleRef:
  kind: Role
  name: data-store-cleaner-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
