apiVersion: v2
name: kubetorch
description: A Helm chart for kubetorch
type: application
version: 0.4.2
appVersion: 0.4.2

dependencies:
  - name: nvidia-device-plugin
    version: "0.14.1"
    repository: https://nvidia.github.io/k8s-device-plugin
    condition: nvidia-device-plugin.enabled

  - name: dcgm-exporter
    version: "4.5.0"
    repository: https://nvidia.github.io/dcgm-exporter/helm-charts
    condition: dcgm-exporter.enabled
