apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubetorch-controller-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubetorch-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kubetorchController.storage.size | default "1Gi" }}
  {{- if .Values.kubetorchController.storage.storageClassName }}
  storageClassName: {{ .Values.kubetorchController.storage.storageClassName }}
  {{- end }}
