apiVersion: v1
kind: Service
metadata:
  name: kubetorch-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-controller
  ports:
    - name: http
      port: {{ .Values.kubetorchController.servicePort | default 8080 }}
      targetPort: 8080
    - name: internal
      port: {{ .Values.kubetorchController.port | default 8081 }}
      targetPort: {{ .Values.kubetorchController.port | default 8081 }}
  type: ClusterIP
