apiVersion: v1
kind: Service
metadata:
  name: kubetorch-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-controller
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: rsync
      port: 8873
      targetPort: 8873
  type: ClusterIP
