{{- if .Values.ephemeralMonitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubetorch-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-prometheus
  ports:
    - port: {{ .Values.ephemeralMonitoring.prometheus.port }}
      targetPort: {{ .Values.ephemeralMonitoring.prometheus.port }}
      name: http
{{- end }}
