{{- if .Values.metrics.enabled }}

{{- /*
Compute metrics ClusterRole name:
- Use plain name in "kubetorch"
- Append namespace elsewhere
*/ -}}
{{- $metricsBaseName := "kubetorch-metrics" }}
{{- $metricsName := $metricsBaseName }}
{{- if ne .Release.Namespace "kubetorch" }}
{{- $metricsName = printf "%s-%s" $metricsBaseName .Release.Namespace }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetorch-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubetorch-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $metricsName }}
  labels:
    app: kubetorch-metrics
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
      - endpoints
      - namespaces
      - configmaps
      - secrets
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-binding" $metricsName }}
  labels:
    app: kubetorch-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $metricsName }}
subjects:
  - kind: ServiceAccount
    name: kubetorch-metrics
    namespace: {{ .Release.Namespace }}
{{- end }}
