{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubetorch-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-metrics
  ports:
    - port: {{ .Values.metrics.prometheus.port }}
      targetPort: {{ .Values.metrics.prometheus.port }}
      name: http
{{- end }}
