{{- if .Values.ephemeralMonitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetorch-grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetorch-grafana
  template:
    metadata:
      labels:
        app: kubetorch-grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.ephemeralMonitoring.grafana.image }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          volumeMounts:
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: dashboards-provider
          configMap:
            name: kubetorch-grafana-dashboard-provider
        - name: datasource
          configMap:
            name: kubetorch-grafana-datasource
        - name: dashboards
          projected:
            sources:
              - configMap:
                  name: kubetorch-grafana-dashboard-provider
              - configMap:
                  name: kubetorch-grafana-dashboard-kubetorch
{{- end }}
