{{- if .Values.ephemeralMonitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubetorch-grafana
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kubetorch-grafana
  ports:
    - port: 3000
      targetPort: 3000
{{- end }}
